//
//  LoginScreenProtocols.swift
//  SampleShop

//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//  This file was generated by Ku Ku Zan.
//

import Foundation
import UIKit

// MARK: - Presenter -> View
protocol LoginScreenPresenterToViewProtocl: BaseViewProtocol {
    func initialControlSetup()
    func showTextFieldErrorLabel(error: ValidationErrors)
}

// MARK: - View -> Presenter
protocol LoginScreenViewToPresenterProtocol: AnyObject {
    func started()
    func clickedLoginButton(inputData: LoginRequestModel)
}

// MARK: - Interactor -> Presenter
protocol LoginScreenInterectorToPresenterProtocol: AnyObject {
    func fetchingStart()
    func success()
    func fail(error: Error)
    func validationFail(_ errorMessage: ValidationErrors)
}

// MARK: - Presenter -> Interactor
protocol LoginScreenPresentorToInterectorProtocol: AnyObject {
    func loginAPICall(inputData: LoginRequestModel)
    func validation(_ inputData: LoginRequestModel) -> Bool
}

// MARK: - Presenter -> Router or WireFrame
protocol LoginScreenPresenterToRouterProtocol: BaseRouterProtocol {
    func navigateToProductScreen()
}
