//
//  LoginScreenEntity.swift
//  SampleShop

//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//  This file was generated by Ku Ku Zan.
//

import Foundation

struct LoginRequestModel: Codable {
    let username: String
    let password: String
}

extension LoginRequestModel: DictionaryConvertible {
    var keyMappingDict: [String: String] {
        [
            "username": "username",
            "password": "password"
        ]
    }
}


struct LoginResponseModel: Codable {
    let token: String
}
