//
//  LoginScreenRouter.swift
//  SampleShop
//

//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import UIKit
import Foundation

class LoginScreenRouter: BaseRouter {
    
    // MARK: - Private properties
    private let storyboard = UIStoryboard(name: "LoginScreen", bundle: nil)
    
    // MARK: Module Setup
    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: LoginScreenViewController.self)
        super.init(viewController: moduleViewController)
        let interactor = LoginScreenInteractor()
        let presenter = LoginScreenPresenter(view: moduleViewController, interactor: interactor, router: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }
    
}

// MARK: - Presenter to Wireframe Interface
extension LoginScreenRouter: LoginScreenPresenterToRouterProtocol {
    
    func navigateToProductScreen() {
        self.viewController.presentView(AllProductScreenRouter())
    }
    
}
