//
//  AllProductScreenProtocols.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import Foundation
import UIKit

// MARK: - Presenter -> View
protocol AllProductScreenPresenterToViewProtocl: BaseViewProtocol {
    func initialControlSetup()
    var productsResponse: ProductsResponseModel? { get set }
}

// MARK: - View -> Presenter
protocol AllProductScreenViewToPresenterProtocol: AnyObject {
    func started()
    func getProducts(_ data: ProductsRequestModel)
    func clickedProductCell(product: Content)
}

// MARK: - Interactor -> Presenter
protocol AllProductScreenInterectorToPresenterProtocol: AnyObject {
    func fetchingStart()
    func success(_ response: ProductsResponseModel)
    func fail(error: Error)
}

// MARK: - Presenter -> Interactor
protocol AllProductScreenPresentorToInterectorProtocol: AnyObject {
    func getProductsAPICall(_ data: ProductsRequestModel)
}

// MARK: - Presenter -> Router or WireFrame
protocol AllProductScreenPresenterToRouterProtocol: BaseRouterProtocol {
    func navigatToProductDetailScreen(_ product: Content)
}


