//
//  AllProductScreenPresenter.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import Foundation
import UIKit

class AllProductScreenPresenter {
    
    // MARK: - Private properties
    private unowned var view: AllProductScreenPresenterToViewProtocl
    private var interactor: AllProductScreenPresentorToInterectorProtocol
    private var router: AllProductScreenPresenterToRouterProtocol
    
    // MARK: - Lifecycle
    init(view: AllProductScreenPresenterToViewProtocl, interactor: AllProductScreenPresentorToInterectorProtocol, router: AllProductScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    
}

// MARK: - View to Presenter
extension AllProductScreenPresenter: AllProductScreenViewToPresenterProtocol {
    
    func started() {
        view.initialControlSetup()
    }
    
    func getProducts(_ data: ProductsRequestModel) {
        interactor.getProductsAPICall(data)
    }
    
    func clickedProductCell(product: Content) {
        router.navigatToProductDetailScreen(product)
    }
    
}

// MARK: - Interactor to Presenter
extension AllProductScreenPresenter: AllProductScreenInterectorToPresenterProtocol {
    
    func fetchingStart() {
        view.showLoading()
    }
    
    func success(_ response: ProductsResponseModel) {
        view.hideLoading()
        view.productsResponse = response
    }
    
    func fail(error: Error) {
        view.hideLoading()
        debugPrint(error)
        if let error = error as? APIError {
            router.showAlert(with: "Error!", message: error.rawValue)
            return
        }
        router.showAlert(with: "Error!", message: error.localizedDescription)
    }
    
}

