//
//  AllProductScreenInteractor.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import Foundation

class AllProductScreenInteractor {
    
    // MARK: Delegate initialization
    var presenter: AllProductScreenInterectorToPresenterProtocol?
    
    // MARK: - Call Service
    func getProductsAPICall(_ data: ProductsRequestModel) {
        presenter?.fetchingStart()
        APIClient.getProducts(productsRequestModel: ProductsRequestModel(page: data.page, size: data.size)) { result in
            switch result {
            case .success(let response):
                self.presenter?.success(response)
            case .failure(let error):
                self.presenter?.fail(error: error)
            }
        }
    }
    
}

// MARK: - Presenter to Interactor
extension AllProductScreenInteractor: AllProductScreenPresentorToInterectorProtocol {
    
}
