//
//  ProductDetailScreenProtocols.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import Foundation
import UIKit

// MARK: - Presenter -> View
protocol ProductDetailScreenPresenterToViewProtocl: BaseViewProtocol {
    func initialControlSetup()
    func setProductData(_ product: Content)
}

// MARK: - View -> Presenter
protocol ProductDetailScreenViewToPresenterProtocol: AnyObject {
    func started()
    func clickedAddToCartButton(_ products: [Content])
    func clickedBackButton()
}

// MARK: - Interactor -> Presenter
protocol ProductDetailScreenInterectorToPresenterProtocol: AnyObject {
    
}

// MARK: - Presenter -> Interactor
protocol ProductDetailScreenPresentorToInterectorProtocol: AnyObject {
    var product: Content { get }
}

// MARK: - Presenter -> Router or WireFrame
protocol ProductDetailScreenPresenterToRouterProtocol: BaseRouterProtocol {
    func navigateToAddToCartScreen(_ products: [Content])
}


