//
//  ProductDetailScreenInteractor.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import Foundation

class ProductDetailScreenInteractor {
    
    // MARK: Delegate initialization
    var presenter: ProductDetailScreenInterectorToPresenterProtocol?
    
    var product: Content
    
    init(_ product: Content) {
        self.product = product
    }
    // MARK: - Call Service
    
}

// MARK: - Presenter to Interactor
extension ProductDetailScreenInteractor: ProductDetailScreenPresentorToInterectorProtocol {
    
}
