//
//  ProductDetailScreenPresenter.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import Foundation
import UIKit

class ProductDetailScreenPresenter {
    
    // MARK: - Private properties
    private unowned var view: ProductDetailScreenPresenterToViewProtocl
    private var interactor: ProductDetailScreenPresentorToInterectorProtocol
    private var router: ProductDetailScreenPresenterToRouterProtocol
    
    // MARK: - Lifecycle
    init(view: ProductDetailScreenPresenterToViewProtocl, interactor: ProductDetailScreenPresentorToInterectorProtocol, router: ProductDetailScreenPresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    
}

// MARK: - View to Presenter
extension ProductDetailScreenPresenter: ProductDetailScreenViewToPresenterProtocol {
    
    func started() {
        view.initialControlSetup()
        view.setProductData(interactor.product)
    }
    
    func clickedBackButton() {
        router.popFromNavigationController(animated: true)
    }
    
    func clickedAddToCartButton(_ products: [Content]) {
        router.navigateToAddToCartScreen(products)
    }
    
}

// MARK: - Interactor to Presenter
extension ProductDetailScreenPresenter: ProductDetailScreenInterectorToPresenterProtocol {
    
}

