//
//  ProductDetailScreenRouter.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import UIKit
import Foundation

class ProductDetailScreenRouter: BaseRouter {
    
    // MARK: - Private properties
    private let storyboard = UIStoryboard(name: "ProductDetailScreen", bundle: nil)
    
    // MARK: Module Setup
    init(_ product: Content) {
        let moduleViewController = storyboard.instantiateViewController(ofType: ProductDetailScreenViewController.self)
        super.init(viewController: moduleViewController)
        let interactor = ProductDetailScreenInteractor(product)
        let presenter = ProductDetailScreenPresenter(view: moduleViewController, interactor: interactor, router: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }
    
}

// MARK: - Presenter to Wireframe Interface
extension ProductDetailScreenRouter: ProductDetailScreenPresenterToRouterProtocol {
    
    func navigateToAddToCartScreen(_ products: [Content]) {
        self.navigationController?.pushView(CartScreenRouter(products))
    }
    
}
