//
//  CartScreenViewController.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import Foundation
import UIKit

class CartScreenViewController: UIViewController {
    
    // MARK: Delegate initialization
    var presenter: CartScreenViewToPresenterProtocol?
    
    // MARK: Outlets
    @IBOutlet weak var productTableView: UITableView!
    @IBOutlet weak var subTotalAmountLabel: UILabel!
    @IBOutlet weak var ctAmountLabel: UILabel!
    @IBOutlet weak var totalAmountLabel: UILabel!
    
    // MARK: Custom initializers go here
    var products: [Content] = [] {
        didSet {
            calculateAmount(products: products)
            productTableView.reloadData()
        }
    }
    
    // MARK: View Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.started()
    }
    
    // MARK: User Interaction - Actions & Targets
    @IBAction func checkOutButtonAction(_ sender: CustomButton) {
        presenter?.clickedCheckOutButtton()
    }
    
    // MARK: Additional Helpers
    private func defaultSetup() {
        self.title = "Cart"
        tableViewSetup()
    }
    
    private func tableViewSetup() {
        productTableView.registerCell(type: ProductTableViewCell.self)
        productTableView.delegate = self
        productTableView.dataSource = self
    }
    
    private func calculateAmount(products: [Content]) {
        let subAmount = products.map({ $0.amount }).reduce(0, +)
        let ct = (subAmount * 5) / 100
        let total = subAmount + ct
        subTotalAmountLabel.text = "\(subAmount) MMK"
        ctAmountLabel.text = "\(ct) MMK"
        totalAmountLabel.text = "\(total) MMK"
    }
}

// MARK: - Extension
/**
 - Documentation for purpose of extension
 */
// MARK: - UITableViewDelegate & UITableViewDataSource
extension CartScreenViewController: UITableViewDataSource, UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return products.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueCell(withType: ProductTableViewCell.self, for: indexPath) as? ProductTableViewCell else {
            return UITableViewCell()
        }
        cell.configCell(product: products[indexPath.row])
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        debugPrint(products[indexPath.row])
    }
    
}

// MARK: - Presenter to View
extension CartScreenViewController: CartScreenPresenterToViewProtocl {
    
    func initialControlSetup() {
        defaultSetup()
    }
    
}
