//
//  CartScreenInteractor.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import Foundation

class CartScreenInteractor {
    
    // MARK: Delegate initialization
    var presenter: CartScreenInterectorToPresenterProtocol?
    
    var products: [Content]
    
    init(_ products: [Content]) {
        self.products = products
    }
    
    // MARK: - Call Service
    
}

// MARK: - Presenter to Interactor
extension CartScreenInteractor: CartScreenPresentorToInterectorProtocol {
   
}
