//
//  CartScreenProtocols.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import Foundation
import UIKit

// MARK: - Presenter -> View
protocol CartScreenPresenterToViewProtocl: BaseViewProtocol {
    func initialControlSetup()
    var products: [Content] { get set }
}

// MARK: - View -> Presenter
protocol CartScreenViewToPresenterProtocol: AnyObject {
    func started()
    func clickedCheckOutButtton()
}

// MARK: - Interactor -> Presenter
protocol CartScreenInterectorToPresenterProtocol: AnyObject {
    
}

// MARK: - Presenter -> Interactor
protocol CartScreenPresentorToInterectorProtocol: AnyObject {
    var products: [Content] { get }
}

// MARK: - Presenter -> Router or WireFrame
protocol CartScreenPresenterToRouterProtocol: BaseRouterProtocol, ConfirmPopupDelegate {
    func showConfirmPopup()
}


