//
//  CartScreenRouter.swift
//  SampleShop
//
//  Created Ku Ku Zan on 19/04/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Ku Ku Zan.
//

import UIKit
import Foundation

class CartScreenRouter: BaseRouter {
    
    // MARK: - Private properties
    private let storyboard = UIStoryboard(name: "CartScreen", bundle: nil)
    
    // MARK: Module Setup
    init(_ products: [Content]) {
        let moduleViewController = storyboard.instantiateViewController(ofType: CartScreenViewController.self)
        super.init(viewController: moduleViewController)
        let interactor = CartScreenInteractor(products)
        let presenter = CartScreenPresenter(view: moduleViewController, interactor: interactor, router: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }
    
}

// MARK: - Presenter to Wireframe Interface
extension CartScreenRouter: CartScreenPresenterToRouterProtocol {
    
    func didPressButton() {
        self.navigationController?.popToRootViewController(animated: true)
    }
    
    func showConfirmPopup() {
        let confirmPopupVC = OrderConfirmStatusViewController()
        confirmPopupVC.delegate = self
        confirmPopupVC.modalPresentationStyle = .overCurrentContext
        confirmPopupVC.modalTransitionStyle = .crossDissolve
        self.viewController.present(confirmPopupVC, animated: true)
    }
    
}
